version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env.example
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: ramengor/kittygram_backend
    env_file: .env.example
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media

  frontend:
    image: ramengor/kittygram_frontend
    env_file: .env.example
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static

  gateway:
    image: ramengor/kittygram_gateway
    env_file: .env.example
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
